### ISSUE TITLE
qb-target

### ISSUE THREAD

**Issue by ziokoko** [Mobius1/ms-spycams#2]
Can anyone make it for qb-target....not ox?

**Comment by Mobius1** [comment]
I'll add the option for qb-target in the next update

**Comment by ziokoko** [comment]
Okay. :) Can't wait!!!!

**Comment by Mobius1** [comment]
I don't have `qb-target` installed on my dev server so I can't test it, but I've pushed an update to the main branch which has support for it. Feel free to test it.

**Comment by ziokoko** [comment]
Can't start because of the Could not find dependency ox_target for resource ms-spycams.

**Comment by Mobius1** [comment]
Change this in `fxmanifest.lua`:

```lua
dependencies {
    'qb-core',
    'ox_target',
}
```

to 

```lua
dependencies {
    'qb-core',
    -- 'ox_target',
}
```

Then change this in `config/config_client.lua`

```lua
Config.TargetLib        = 'ox'
```

to

```lua
Config.TargetLib        = 'qb'
```

**Comment by Mobius1** [comment]
Re-open if needed
